"""empty message

Revision ID: 064804aca68b
Revises: 1c14e9c3d92b
Create Date: 2021-03-18 17:50:19.105291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064804aca68b'
down_revision = '1c14e9c3d92b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.String(length=60), nullable=False),
    sa.Column('payment_amount', sa.Integer(), nullable=False),
    sa.Column('date_booking', sa.DateTime(), nullable=True),
    sa.Column('date_for_booking', sa.DateTime(), nullable=True),
    sa.Column('partition_no', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('course_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_name',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('courseName', sa.VARCHAR(length=40), nullable=False),
    sa.Column('courseId', sa.VARCHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('courseId'),
    sa.UniqueConstraint('courseName')
    )
    op.drop_table('bookings')
    # ### end Alembic commands ###
