"""empty message

Revision ID: 11dcd24c20b2
Revises: 34d59567a191
Create Date: 2021-04-06 21:35:02.511632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11dcd24c20b2'
down_revision = '34d59567a191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'unique_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'unique_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
