"""empty message

Revision ID: 14b4f53c9746
Revises: c28e9dffac46
Create Date: 2021-03-30 01:07:49.947125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b4f53c9746'
down_revision = 'c28e9dffac46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('property', sa.Column('contact_front', sa.Integer(), nullable=True))
    op.add_column('property', sa.Column('contact_manager', sa.Integer(), nullable=True))
    op.add_column('property', sa.Column('owner_name', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'owner_name')
    op.drop_column('property', 'contact_manager')
    op.drop_column('property', 'contact_front')
    op.drop_column('property', 'capacity')
    # ### end Alembic commands ###
