"""empty message

Revision ID: 1a7f40fdbeef
Revises: 14b4f53c9746
Create Date: 2021-03-30 01:10:55.825651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a7f40fdbeef'
down_revision = '14b4f53c9746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('enlistment_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'enlistment_status')
    # ### end Alembic commands ###
