"""empty message

Revision ID: 1b930f2f3e57
Revises: 
Create Date: 2021-04-06 21:25:57.781142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b930f2f3e57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('unique_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['unique_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'unique_id')
    # ### end Alembic commands ###
