"""empty message

Revision ID: 26fe9c94ae6a
Revises: 11dcd24c20b2
Create Date: 2021-04-06 21:49:19.208496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26fe9c94ae6a'
down_revision = '11dcd24c20b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'unique_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=120),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'unique_id',
               existing_type=sa.String(length=120),
               type_=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
