"""empty message

Revision ID: 4513b536f626
Revises: 86d177e9fe61
Create Date: 2021-05-07 14:35:18.632010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4513b536f626'
down_revision = '86d177e9fe61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('no_adults', sa.Integer(), nullable=True))
    op.alter_column('user', 'unique_id',
               existing_type=sa.VARCHAR(length=120),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'unique_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('bookings', 'no_adults')
    # ### end Alembic commands ###
