"""empty message

Revision ID: 47451f752508
Revises: 26fe9c94ae6a
Create Date: 2021-05-01 22:10:49.542625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47451f752508'
down_revision = '26fe9c94ae6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profile_img',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('user', 'unique_id',
               existing_type=sa.VARCHAR(length=120),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'unique_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'profile_img',
               existing_type=sa.String(length=500),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    # ### end Alembic commands ###
