"""empty message

Revision ID: 496e1a3acd58
Revises: 1b930f2f3e57
Create Date: 2021-04-06 21:28:47.337111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496e1a3acd58'
down_revision = '1b930f2f3e57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'unique_id',
               existing_type=sa.INTEGER(),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'unique_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
