"""empty message

Revision ID: a0eaca1bacb4
Revises: 186e6fd23613
Create Date: 2021-05-05 15:26:20.108596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0eaca1bacb4'
down_revision = '186e6fd23613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('image', sa.String(length=1000), nullable=True))
    op.alter_column('user', 'unique_id',
               existing_type=sa.VARCHAR(length=120),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'unique_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('property', 'image')
    # ### end Alembic commands ###
