"""empty message

Revision ID: aa7e8e2a772f
Revises: a0eaca1bacb4
Create Date: 2021-05-07 01:10:32.835883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa7e8e2a772f'
down_revision = 'a0eaca1bacb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('arrival_data', sa.Date(), nullable=True))
    op.add_column('bookings', sa.Column('depature_data', sa.Date(), nullable=True))
    op.alter_column('user', 'unique_id',
               existing_type=sa.VARCHAR(length=120),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'unique_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('bookings', 'depature_data')
    op.drop_column('bookings', 'arrival_data')
    # ### end Alembic commands ###
