"""empty message

Revision ID: c28e9dffac46
Revises: 064804aca68b
Create Date: 2021-03-18 18:26:19.922187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c28e9dffac46'
down_revision = '064804aca68b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('payment_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'payment_status')
    # ### end Alembic commands ###
