"""empty message

Revision ID: f2b4cb9f8e1f
Revises: 47451f752508
Create Date: 2021-05-05 01:18:43.349337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b4cb9f8e1f'
down_revision = '47451f752508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property', 'pan_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('user', 'unique_id',
               existing_type=sa.VARCHAR(length=120),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'unique_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('property', 'pan_number',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
