"""empty message

Revision ID: 1c14e9c3d92b
Revises: 
Create Date: 2021-03-13 20:56:59.245188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c14e9c3d92b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('property_name', sa.String(length=60), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('best_price', sa.Integer(), nullable=True),
    sa.Column('pan_number', sa.Integer(), nullable=True),
    sa.Column('partitions', sa.Integer(), nullable=True),
    sa.Column('features', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    # ### end Alembic commands ###
